### ISSUE TITLE
50 changes and phototypesetter version 7

### ISSUE THREAD

**Issue by jonathangray** [pcollinson/unixv6-extras#1]
Thank-you for putting together this repository.    The "new" archive format found in cont.a was distributed as part of the phototypesetter version 7, PWB/UNIX 1.0 and USENIX tapes.

In case you are interested in a newer kernel and toolchain than released v6:

# 50 changes

Regarding your letter from 1979 reprinted in [AUUGN vol 1 no 3](https://archive.org/details/AUUGN_V01_3/page/n29/mode/2up)

> I came across a directory called 'v6unix' which contains a new 'Bell' labs UNIX base system.

and the [50 changes](https://archive.org/details/unix_news_november-1976)

> I got the "diff" listing of all changes to Bell Unix system proper from
> "standard" version 6, which apparently means the currently distributed
> version 6. There are some bug fixes which are not in my version 6, which
> are in the currently distributed v6.  Anyway, I've itemized some
> 50 changes, and sent the list to Ken for verification and comments.

see
```
tuhs/Applications/Spencer_Tapes/unsw3.tar.gz
usr/sys/v6unix/
```

# phototypesetter version 7

[UNIX News May-June 1976](https://archive.org/details/unix_news_may-june-1976/page/n1/mode/2up)

> New archiver - includes "ar.c", new "ld.c" which reads the new style,
> and "arcv.c" which converts from old to new formats. The stinker is that
> "ar.c" uses long (double-word) integers, which can only be compiled by
> the new C compiler which we can't distribute yet. Therefore, executable
> modules are included.

see
```
tuhs/Applications/Usenix_77/ug091377.tar.gz
1/new_ar/

tuhs/Tools/Tapes/newoldar.*
```

[UNIX News November 1976](https://archive.org/details/unix_news_november-1976/)

> Also, a new tape is in the process of preparation, and should be
> available as soon as it clears the lawyers, for the usual free license
> and handling fee. It contains the new nroff, the new C, the new
> I/O library (faster & smaller than anything to date), and a bunch of
> other such things."

[;login: August 1977](https://archive.org/details/login_august-1977/page/n21/mode/2up)

> The principal speaker at the Phototypesetting session was Joe Ossanna.
> He announced a new phototypesetting package, typesetter V7, which is or
> soon will be available from Western Electric for a $3300 license fee.

A phototypesetter v7 license was required for the modified stdio/libS
distributed with 2BSD. [AUUGN Vol 1 No 3](https://archive.org/details/AUUGN_V01_3/page/n27/mode/2up)

> In order to get the new nroff/troff macro package and the "stdio" modifications, you must include
> a copy of your license for the version 7 phototypesetter package.

not the phototypesetter tape, but see
```
tuhs/Applications/Spencer_Tapes/unsw3.tar.gz
usr/source/c_compiler/
usr/source/stdio/
```

```
tuhs/Distributions/Other/Interdata/interdata_v6.tar.gz
usr/source/stdio/
usr/source/troff
usr/doc/cdoc/newstuff.nr
```

As the interdata v6 has yet another ar format, I used a modified version
of rdar to extract source in some of the archives.

**Comment by pcollinson** [comment]
Thanks for this. My intention was to replicate the 'original' bistro, but add in the terminal handler. On the way some other things got added.

The UNSW 'changes' tape was a great source of ideas and changes. Many were integrated into the system that UKC was running at that time.

**Comment by jonathangray** [comment]
Indeed I see many references to UNSW  looking at the files in Collinson_v6.  Your afterword to the Peer-to-Peer version of the commentary also touches on it and the terminal driver.  Though there it is stated it was originally from the Boston Children's  museum and the git repository has it as UCLA.   Which matches the USENIX tapes in the TUHS archive:

> Designed and coded by Mark Kampe, UCLA-ATS, March 1976
> in response to the need for variable break characters, improved
> editing abilities, more general special functions and general
> sexier behavior.

I mostly wanted to mention the archive files, so I'll close this.
